'use client'

import { useMemo, useState } from 'react'
import {
  Archive, BriefcaseBusiness, CalendarDays, Check, ChevronLeft, ChevronRight,
  Clock3, Eye, FileText, Filter, Globe2, LayoutList, Link2,
  MoreHorizontal, Paperclip, Search, Sparkles, UserRound,
  X, CheckCircle2, CircleAlert,
} from 'lucide-react'

const profiles = [
  { id: 'gary', name: 'Gary Gribble', initials: 'GG', role: 'DevOps Engineer', color: 'bg-slate-900' },
  { id: 'sarah', name: 'Sarah Chen', initials: 'SC', role: 'Product Designer', color: 'bg-primary' },
  { id: 'michael', name: 'Michael Ross', initials: 'MR', role: 'Data Engineer', color: 'bg-slate-600' },
]

const applications = [
  { id: 1, profileId: 'gary', bidderName: 'Gary Gribble', company: 'EPAM Systems', title: 'Senior DevOps Engineer', status: 'Qualified', stage: 'Manually Completed', posted: '20 hours ago', date: 'Today', type: 'Dev', location: 'United States', color: 'bg-slate-900', accent: 'border-primary/25 bg-primary/[0.025]', score: '92%' },
  { id: 2, profileId: 'gary', bidderName: 'Gary Gribble', company: 'C5MI Insight', title: 'Senior SAP Extended Warehouse Management Developer', status: 'Disqualified', stage: 'Not Applied', posted: '6 months ago', date: 'Jun 12, 2025', type: 'Dev', location: 'Germany', color: 'bg-slate-600', accent: '', score: '61%' },
  { id: 3, profileId: 'gary', bidderName: 'Gary Gribble', company: 'C5MI Insight', title: 'SAP BTP/UI5 Developer', status: 'Disqualified', stage: 'Not Applied', posted: '4 months ago', date: 'Aug 28, 2025', type: 'Dev', location: 'United States', color: 'bg-slate-600', accent: '', score: '54%' },
  { id: 4, profileId: 'gary', bidderName: 'Gary Gribble', company: 'EPAM Systems', title: 'Cloud Platform Architect', status: 'Qualified', stage: 'Manually Completed', posted: 'Yesterday', date: 'Yesterday', type: 'Architect', location: 'United Kingdom', color: 'bg-slate-900', accent: '', score: '87%' },
]

const tabs = [
  ['jd', 'JD', ''], ['resume', 'Resume', 'Tailored'], ['cover', 'Cover Letter', ''], ['qa', 'QA', '9'], ['screens', 'Screenshots', ''],
] as const

function Pill({ children, tone = 'muted' }: { children: React.ReactNode; tone?: 'green' | 'orange' | 'blue' | 'muted' }) {
  const colors = { green: 'border-green-200 bg-green-50 text-green-700', orange: 'border-orange-200 bg-orange-50 text-orange-700', blue: 'border-blue-100 bg-blue-50 text-blue-700', muted: 'border-border bg-muted text-muted-foreground' }
  return <span className={`rounded-full border px-2 py-1 text-[11px] font-semibold ${colors[tone]}`}>{children}</span>
}

export function ApplicationReviewView() {
  const [selected, setSelected] = useState(1)
  const [checked, setChecked] = useState<number[]>([1])
  const [selectedProfiles, setSelectedProfiles] = useState<string[]>(['gary'])
  const [query, setQuery] = useState('')
  const [tab, setTab] = useState('jd')
  const [dateOpen, setDateOpen] = useState(false)
  const [weekOpen, setWeekOpen] = useState(false)
  const [bidderOpen, setBidderOpen] = useState(false)
  const [profileOpen, setProfileOpen] = useState(false)
  const [startDate, setStartDate] = useState('')
  const [endDate, setEndDate] = useState('')
  const [selectedBidder, setSelectedBidder] = useState('All bidders')
  const current = applications.find((item) => item.id === selected) ?? applications[0]
  const filtered = useMemo(() => applications.filter((item) => selectedProfiles.includes(item.profileId) && `${item.title} ${item.company} ${item.bidderName}`.toLowerCase().includes(query.toLowerCase())), [query, selectedProfiles])
  const toggle = (id: number) => setChecked((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])
  const toggleProfile = (id: string) => setSelectedProfiles((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])

  return (
    <main className="flex min-h-0 flex-1 flex-col">
      <header className="flex flex-col gap-4 border-b border-border bg-background px-6 py-5 lg:flex-row lg:items-center lg:justify-between lg:px-8">
        <div><p className="mb-1 text-xs font-semibold uppercase tracking-[0.14em] text-primary">Workspace</p><h1 className="text-2xl font-extrabold tracking-tight">Application review</h1><p className="mt-1 text-sm text-muted-foreground">Review, compare, and organize your submitted applications.</p></div>
        <div className="flex flex-wrap items-center gap-2">
          <div className="relative"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search applications..." className="h-10 w-56 rounded-lg border border-input bg-card pl-9 pr-3 text-sm outline-none ring-primary/20 placeholder:text-muted-foreground focus:ring-4" /></div>
          <button type="button" aria-label="More options" className="grid size-10 place-items-center rounded-lg border border-input bg-card"><MoreHorizontal className="size-4" /></button>
        </div>
      </header>
      <div className="flex flex-wrap items-center gap-2 border-b border-border bg-muted/30 px-6 py-3 text-sm lg:px-8"><span className="font-semibold">Filter by:</span><div className="relative"><button type="button" onClick={() => { setDateOpen(!dateOpen); setWeekOpen(false); setBidderOpen(false) }} className="flex items-center gap-2 rounded-lg border bg-card px-3 py-2">{startDate && endDate ? `${startDate} – ${endDate}` : 'Date range'} <CalendarDays className="size-3.5 text-muted-foreground" /></button>{dateOpen && <div className="motion-slide-down absolute top-full left-0 z-20 mt-2 flex gap-2 rounded-xl border border-border bg-card p-3 shadow-lg"><label className="text-xs font-semibold text-muted-foreground">Start<input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} className="mt-1 block rounded-md border px-2 py-1.5 text-sm font-normal" /></label><label className="text-xs font-semibold text-muted-foreground">End<input type="date" value={endDate} onChange={(e) => setEndDate(e.target.value)} className="mt-1 block rounded-md border px-2 py-1.5 text-sm font-normal" /></label></div>}</div><div className="relative"><button type="button" onClick={() => { setWeekOpen(!weekOpen); setDateOpen(false); setBidderOpen(false) }} className="rounded-lg border bg-card px-3 py-2">This week</button>{weekOpen && <div className="motion-slide-down absolute top-full left-0 z-20 mt-2 w-40 rounded-xl border border-border bg-card p-1.5 shadow-lg">{['This week', 'Last week', 'This month', 'All time'].map((week) => <button key={week} type="button" onClick={() => setWeekOpen(false)} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-accent">{week}</button>)}</div>}</div><div className="relative"><button type="button" onClick={() => { setBidderOpen(!bidderOpen); setDateOpen(false); setWeekOpen(false) }} className="hidden items-center gap-2 rounded-lg border bg-card px-3 py-2">{selectedBidder} <UserRound className="size-3.5 text-muted-foreground" /></button>{bidderOpen && <div className="absolute top-full left-0 z-20 mt-2 w-48 rounded-xl border border-border bg-card p-1.5 shadow-lg">{['All bidders', ...profiles.map((profile) => profile.name)].map((bidder) => <button key={bidder} type="button" onClick={() => { setSelectedBidder(bidder); setBidderOpen(false) }} className="block w-full rounded-lg px-3 py-2 text-left text-sm hover:bg-accent">{bidder}</button>)}</div>}</div><button type="button" onClick={() => { setStartDate(''); setEndDate(''); setSelectedBidder('All bidders') }} className="ml-auto text-xs font-semibold text-primary">Clear all</button></div>

      <div className="flex min-h-0 flex-1 flex-col xl:flex-row">
        <aside className="flex w-full shrink-0 flex-col border-b border-border bg-card/50 xl:w-[390px] xl:border-r xl:border-b-0">
          <div className="relative flex flex-col border-b border-border px-5 py-4">
            <div className="flex items-center justify-between"><div><p className="text-[11px] font-semibold uppercase tracking-wider text-primary">Review profiles</p><h2 className="mt-1 font-bold">Select profiles</h2></div><span className="rounded-full bg-accent px-2 py-1 text-[11px] font-semibold text-primary">{selectedProfiles.length} selected</span></div>
            <div className="relative order-2 mt-3"><button type="button" onClick={() => setProfileOpen(!profileOpen)} aria-expanded={profileOpen} className="flex w-full items-center justify-between rounded-lg border border-input bg-card px-3 py-2.5 text-left text-sm hover:border-primary/50"><span className="text-muted-foreground">Select profiles</span><span className="flex items-center gap-2"><span className="text-xs font-semibold text-primary">{selectedProfiles.length} selected</span><ChevronRight className="size-4 rotate-90 text-muted-foreground" /></span></button><div className="mt-2 flex items-center gap-3 px-1"><button type="button" onClick={() => setSelectedProfiles(profiles.map((profile) => profile.id))} className="text-xs font-semibold text-primary hover:underline">Select all</button><button type="button" onClick={() => setSelectedProfiles([])} className="text-xs font-semibold text-muted-foreground hover:text-foreground hover:underline">Unselect all</button></div>{profileOpen && <div onMouseLeave={() => setProfileOpen(false)} className="motion-pop-in absolute top-full left-0 right-0 z-10 mt-12 rounded-xl border border-border bg-card p-2 shadow-lg">{profiles.map((profile) => <button key={profile.id} type="button" onClick={() => toggleProfile(profile.id)} aria-pressed={selectedProfiles.includes(profile.id)} className="flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left hover:bg-accent"><span className={`grid size-7 place-items-center rounded-md ${profile.color} text-[9px] font-bold text-white`}>{profile.initials}</span><span className="min-w-0 flex-1"><span className="block truncate text-xs font-semibold">{profile.name}</span><span className="block truncate text-[10px] text-muted-foreground">{profile.role}</span></span>{selectedProfiles.includes(profile.id) && <Check className="size-4 text-primary" />}</button>)}</div>}</div><div className="order-1 mt-2 flex gap-1.5 overflow-x-auto pb-1">{profiles.filter((profile) => selectedProfiles.includes(profile.id)).map((profile) => <div key={profile.id} className="flex shrink-0 items-center gap-1.5 rounded-lg border border-primary/25 bg-accent/50 px-2 py-1.5"><span className={`grid size-5 place-items-center rounded-md ${profile.color} text-[8px] font-bold text-white`}>{profile.initials}</span><span className="text-[11px] font-semibold">{profile.name}</span><button type="button" onClick={() => toggleProfile(profile.id)} aria-label={`Remove ${profile.name}`} className="text-primary"><X className="size-3" /></button></div>)}</div>
          </div>
          <div className="flex items-center justify-between border-b border-border px-5 py-4"><div><h2 className="font-bold">Applications</h2><p className="mt-0.5 text-xs text-muted-foreground">{filtered.length} applications found</p></div><button type="button" className="rounded-md p-2 text-muted-foreground hover:bg-muted" aria-label="List options"><LayoutList className="size-4" /></button></div>
          <div className="flex gap-2 overflow-x-auto p-4 xl:flex-col xl:overflow-y-auto">{filtered.map((item) => <article key={item.id} onClick={() => setSelected(item.id)} className={`interactive-surface relative min-w-[310px] cursor-pointer rounded-xl border p-3.5 transition-all xl:min-w-0 ${selected === item.id ? 'border-primary bg-accent/35 shadow-sm' : 'border-border bg-card hover:border-primary/40'}`}><div className="flex gap-3"><div className={`-ml-1 grid size-9 shrink-0 place-items-center rounded-lg ${profiles.find((profile) => profile.id === item.profileId)?.color ?? 'bg-muted'} text-[10px] font-bold text-white`}>{profiles.find((profile) => profile.id === item.profileId)?.initials}</div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><h3 className="truncate text-sm font-bold">{item.title}</h3></div><p className="mt-1 truncate text-xs text-muted-foreground">{item.company}</p></div></div><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><UserRound className="size-3.5" />Applied by <strong className="font-bold text-primary">{item.bidderName}</strong></span></div><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Clock3 className="size-3.5" />Posted {item.posted}</span></div></article>)}</div><div className="mt-auto hidden items-center justify-center gap-6 border-t border-border py-4 text-sm xl:flex"><ChevronLeft className="size-4 text-muted-foreground" /><span className="grid size-9 place-items-center rounded-lg border border-primary text-primary">1</span><ChevronRight className="size-4 text-muted-foreground" /></div>
        </aside>

        <section className="min-w-0 flex-1 bg-background"><div className="border-b border-border bg-card px-6 py-5 lg:px-8"><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><div className="grid size-11 place-items-center rounded-xl bg-slate-900 text-xs font-bold text-white">GG</div><div><h2 className="text-lg font-extrabold">{current.title}</h2><p className="text-sm text-muted-foreground">{current.company}</p><div className="mt-3 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="flex items-center gap-1.5"><Globe2 className="size-3.5" />{current.location}</span><span className="flex items-center gap-1.5"><BriefcaseBusiness className="size-3.5" />Full Time</span><span className="flex items-center gap-1.5"><Sparkles className="size-3.5" />{current.type}</span></div></div></div><div className="flex items-center gap-2"><button className="grid size-9 place-items-center rounded-lg border border-input bg-card" aria-label="View application"><Eye className="size-4" /></button></div></div><nav className="mt-5 flex gap-1 overflow-x-auto" aria-label="Application details tabs">{tabs.map(([value, label, badge]) => <button key={value} type="button" onClick={() => setTab(value)} className={`flex shrink-0 items-center gap-2 border-b-2 px-3 py-2 text-sm font-medium transition-colors ${tab === value ? 'border-primary text-primary' : 'border-transparent text-muted-foreground hover:text-foreground'}`}><FileText className="size-4" />{label}{badge && <span className="rounded-full bg-accent px-2 py-0.5 text-[10px] font-bold text-primary">{badge}</span>}</button>)}</nav></div><DetailContent tab={tab} current={current} /></section>
      </div>
    </main>
  )
}

function DetailContent({ tab, current }: { tab: string; current: typeof applications[number] }) {
  if (tab === 'form') return <div className="mx-auto max-w-3xl space-y-4 p-6 lg:p-8"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">Application form</p><h3 className="mt-1 text-lg font-bold">Candidate responses</h3></div><span className="flex items-center gap-1.5 text-xs font-semibold text-green-600"><CheckCircle2 className="size-4" />Complete</span></div>{[['Years of relevant experience', '8'], ['Notice period', 'Available now'], ['Primary skill', 'Amazon Web Services'], ['Preferred work countries', 'United States of America'], ['Current country of residence', current.location]].map(([label, value]) => <div key={label} className="rounded-xl border border-border bg-card p-4"><div className="mb-3 flex items-center justify-between"><span className="text-sm font-semibold">{label}</span><button aria-label={`Edit ${label}`} className="text-xs text-primary hover:underline">Edit</button></div><div className="rounded-lg border border-border bg-muted/60 px-3.5 py-2.5 text-sm text-muted-foreground">{value}</div></div>)}</div>
  const content = { resume: ['Tailored resume', 'Senior DevOps Engineer with 8+ years building resilient cloud infrastructure, automating delivery pipelines, and improving developer velocity.'], cover: ['Cover letter', 'I am excited to bring my experience in cloud platforms and continuous delivery to the EPAM Systems team. My background aligns closely with this role and its focus on scalable engineering.'], jd: ['Job description', 'Own the design and operation of cloud infrastructure. Collaborate with engineering teams to improve reliability, security, and deployment workflows.'], qa: ['Form snapshots', '9 questions answered. Review the original responses submitted with this application.'], screens: ['Application screenshots', 'Screenshots captured during the application process.'] }[tab as 'resume' | 'cover' | 'jd' | 'qa' | 'screens']
  return <div className="mx-auto max-w-3xl p-6 lg:p-8"><div className="rounded-xl border border-border bg-card p-6"><div className="mb-5 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-lg bg-accent text-primary"><Paperclip className="size-4" /></div><div><p className="text-xs font-semibold uppercase tracking-wider text-primary">{content?.[0]}</p><h3 className="mt-1 text-lg font-bold">{tab === 'resume' ? (profiles.find((profile) => profile.id === current.profileId)?.name ?? 'Applicant profile') : current.title}</h3></div></div><p className="text-sm leading-7 text-muted-foreground">{content?.[1]}</p><div className="mt-6 flex gap-2"><button className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold"><Eye className="size-4" /> Preview</button><button className="flex items-center gap-2 rounded-lg bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground"><Link2 className="size-4" /> Open document</button></div></div></div>
}
